default_connection_name = "default" 

[cli.logs]
save_logs = true
path = "/home/codespace/.config/snowflake/logs"
level = "info"

[connections]
[connections.default]
account = "pbzsblp-dev_account"
user = "BADGEFOUR"
password = "44Badge44D"
database = "DEMO_DB"
schema = "PUBLIC"
warehouse = "COMPUTE_WH"