name: Deploy DE Project Snowpark Apps

# Controls when the action will run. 
on:
  push:
    branches:
      - devenv3

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: snowpark_demo
          environment-file: environment.yml

      - name: Conda info
        shell: bash -el {0}
        run: conda info


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Deploy Snowpark apps
        working-directory: first_snowpark2_project
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          # SNOWFLAKE_CONNECTIONS_my_test_connection_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          # SNOWFLAKE_CONNECTIONS_my_test_connection_USER: ${{ secrets.SNOWFLAKE_USER }}
          # SNOWFLAKE_CONNECTIONS_my_test_connection_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          # SNOWFLAKE_CONNECTIONS_my_test_connection_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          # SNOWFLAKE_CONNECTIONS_my_test_connection_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          # SNOWFLAKE_CONNECTIONS_my_test_connection_DATABASE: "demo_db"
        # run: echo $SNOWFLAKE_CONNECTIONS_my_test_connection_ACCOUNT
        run: python deploy_snowpark_app.py $GITHUB_WORKSPACE/first_snowpark2_project

      - name: cliaction
        uses: Snowflake-Labs/snowflake-cli-action@v1.5 
        with:
            cli-version: "latest"
            default-config-file-path: "config.toml"
        
          # Use the CLI
      - name: Test version
        run: |
           snow --version
           snow connection test

      - name: deploy code
        working-directory: first_snowpark_project
        run: |
            snow snowpark \
                 deploy --replace \
                  --temporary-connection \
                  --account $SNOWFLAKE_ACCOUNT \
                  --user pradeep \
                  --database $SNOWFLAKE_DATABASE \
                  --role $SNOWFLAKE_ROLE \
                  --warehouse "COMPUTE_WH"
      # - name: run snow
      #   run: snow snowpark build
           
